HC/HC/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),

]

HC/home/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
app_name = 'home'

urlpatterns = [
    url(r'^$', views.homepage,name='home'),
    url(r'^detail/(?P<id>[\w-]+)/$', views.detail, name='detail'),
]

urlpatterns += staticfiles_urlpatterns()

HC/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^', include('home.urls')),
    url(r'^disease/', include('disease.urls')),
]

urlpatterns += staticfiles_urlpatterns()

account/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'account'

urlpatterns = [

    url(r'^signup/pat/$', views.signup_p, name='signup_p'),
    url(r'^signup_pat/$', views.signup_pat, name='signup_pat'),
    url(r'^login_pat/$', views.login_pat, name='login_pat'),
    url(r'^login/pat/$', views.login_p, name='login_p'),

    url(r'^signup/doc/$', views.signup_d, name='signup_d'),
    url(r'^signup_doc/$', views.signup_doc, name='signup_doc'),
    url(r'^login/doc/$', views.login_d, name='login_d'),
    url(r'^login_doc/$', views.login_doc, name='login_doc'),

    url(r'^logout_doc/$', views.logout_doc, name='logout_doc'),
    url(r'^pat_details/$', views.pat_deatil, name='pat_details'),
    url(r'^record/$', views.record, name='record'),
    url(r'^record_process/$', views.record_process, name='record_process'),
    url(r'^show_patdetails/$',views.show_patdetail,name='show_patdetails'),
]

home/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
app_name = 'home'

urlpatterns = [
    url(r'^$', views.homepage,name='home'),
    url(r'^detail/(?P<id>[\w-]+)/$', views.detail, name='detail'),
]

urlpatterns += staticfiles_urlpatterns()

HC/home/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

HC/home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from account.models import Patient


def homepage(request):
    return render(request, 'home/index.html')


def detail(request,id):
    p=Patient.objects.all().get(aadhar_no=id)
    return render(request,"home/dashboard.html",{"data":p})

home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from account.models import Patient


def homepage(request):
    return render(request, 'home/index.html')


def detail(request,id):
    p=Patient.objects.all().get(aadhar_no=id)
    return render(request,"home/dashboard.html",{"data":p})

home/templates/home/base.html
{% load static  %}
<!doctype html>
<html lang="en">

<head>
	{% block pre %} {% endblock %}
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="icon" href="img/favicon.png" type="image/png">
	<title>{% block title %} {% endblock %}</title>

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}">
	<link rel="stylesheet" href="vendors/linericon/style.css">
	<link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="vendors/owl-carousel/owl.carousel.min.css">
	<link rel="stylesheet" href="vendors/lightbox/simpleLightbox.css">
	<link rel="stylesheet" href="vendors/nice-select/css/nice-select.css">
	<link rel="stylesheet" href="vendors/animate-css/animate.css">
	<link rel="stylesheet" href="vendors/jquery-ui/jquery-ui.css">
	<!-- main css -->
	<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
	<link rel="stylesheet" href="{% static 'home/css/responsive.css' %}">
</head>

<body style="margin-top: -39px;">
	<!--================Header Menu Area =================-->
	<header class="header_area">
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light" style="background-color: white;">
				<div class="container">
					<a class="navbar-brand logo_h" href="index.html">
						<img src="{% static 'home/img/logo.png' %}" alt="">
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
					 aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
						<div class="row ml-0 w-100">
							<div class="col-lg-12 pr-0">
								<ul class="nav navbar-nav center_nav pull-right">
									<li class="nav-item active">
										<a class="nav-link" href="{% url 'home:home' %}">Home</a>
									</li>
									<li class="nav-item ">
										<a class="nav-link" href="departments.html"></a>
									</li>
									<li class="nav-item ">
										<a class="nav-link" href="doctors.html"></a>
									</li>
									<li class="nav-item submenu dropdown">
										<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">contact us</a>
										<ul class="dropdown-menu">
											<li class="nav-item">
												<a class="nav-link" href="about.html"></a>
											</li>
											<li class="nav-item">
												<a class="nav-link" href="services.html">Services</a>
											</li>
											<li class="nav-item">
												<a class="nav-link" href="elements.html">Elements</a>
											</li>
										</ul>
									</li>
									<li class="nav-item">
											<li class="nav-item">
												<a class="nav-link" href="{% url 'account:login_d' %}">Doctor Login</a>
											</li>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="{% url 'account:login_p' %}">Patient Login</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</nav>
		</div>
	</header>
	<!--================Header Menu Area =================-->

	<!--================ Home Banner Area =================-->
	{% block content %}

    {% endblock %}

	<!--================ End Home Banner Area =================-->

	<!--================ start footer Area =================-->
		<footer class="footer-area">
		<div class="container" style="padding: 10px 0px">
			<div class="row">
				<p class="col-lg-8 col-sm-8 footer-text m-0">
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved ! <i class="fa fa-heart-o" aria-hidden="true"></i><a href="https://colorlib.com" target="_blank"></a>
				</p>
				<div class="col-lg-4 col-sm-12 footer-social">
					<a href="#">
						<i class="fa fa-facebook"></i>
					</a>
					<a href="#">
						<i class="fa fa-twitter"></i>
					</a>
					<a href="#">
						<i class="fa fa-instagram"></i>
					</a>
					<a href="#">
						<i class="fa fa-behance"></i>
					</a>
				</div>
			</div>
		</div>
	</footer>
	<!--================ End footer Area =================-->



	<!--================ Optional JavaScript =================-->
	<!--================ jQuery Popper.js Bootstrap JS =================-->
	<script src="{% static 'home/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'home/js/popper.js' %}"></script>
	<script src="{% static 'home/s/bootstrap.min.js"' %}"></script>
	<script src="vendors/nice-select/js/jquery.nice-select.min.js"></script>
	<script src="vendors/isotope/isotope-min.js"></script>
	<script src="vendors/owl-carousel/owl.carousel.min.js"></script>
	<script src="{% static 'home/js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
	<script src="{% static 'home/js/mail-script.js' %}"></script>
	<script src="{% static 'home/js/custom.js' %}"></script>
</body>

</html>

home/templates/home/base3.html
{% load static  %}
<!doctype html>
<html lang="en">

<head>
	{% block pre %} {% endblock %}
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="icon" href="img/favicon.png" type="image/png">
	<title>{% block title %} {% endblock %}</title>

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}">
	<link rel="stylesheet" href="vendors/linericon/style.css">
	<link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="vendors/owl-carousel/owl.carousel.min.css">
	<link rel="stylesheet" href="vendors/lightbox/simpleLightbox.css">
	<link rel="stylesheet" href="vendors/nice-select/css/nice-select.css">
	<link rel="stylesheet" href="vendors/animate-css/animate.css">
	<link rel="stylesheet" href="vendors/jquery-ui/jquery-ui.css">
	<!-- main css -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'table/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'table/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'table/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'table/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'table/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'table/vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'table/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'table/css/main.css' %}">-->
	<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
	<link rel="stylesheet" href="{% static 'home/css/responsive.css' %}">
</head>

<body style="margin-top: -39px;">
	<!--================Header Menu Area =================-->
	<header class="header_area">
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light" style="background-color: white;">
				<div class="container">
					<a class="navbar-brand logo_h" href="index.html">
						<img src="{% static 'home/img/logo.png' %}" alt="">
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
					 aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
						<div class="row ml-0 w-100">
							<div class="col-lg-12 pr-0">
								<ul class="nav navbar-nav center_nav pull-right">
									<li class="nav-item active">
										<a class="nav-link" href="{% url 'home:home' %}">Home</a>
									</li>
									<li class="nav-item ">
										<a class="nav-link" href="about.html">About</a>
									</li>
									<li class="nav-item ">

										<a class="nav-link" href="{% url 'account:pat_details' %}">Patient Details</a>
									</li>
									<li class="nav-item ">
										<a class="nav-link" href="{% url 'account:record' %}">Add record</a>
									</li>
									<li class="nav-item ">
										<a class="nav-link" href=""></a>
									</li>

									<li class="nav-item">
											<li class="nav-item">
												<a class="nav-link" href="{% url 'account:logout_doc' %}">logout</a>
											</li>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</nav>
		</div>
	</header>
	<!--================Header Menu Area =================-->

	<!--================ Home Banner Area =================-->
	{% block content %}

    {% endblock %}

	<!--================ End Home Banner Area =================-->





	<!--================ Optional JavaScript =================-->
	<!--================ jQuery Popper.js Bootstrap JS =================-->
	<script src="{% static 'home/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'home/js/popper.js' %}"></script>
	<script src="{% static 'home/s/bootstrap.min.js"' %}"></script>
	<script src="vendors/nice-select/js/jquery.nice-select.min.js"></script>
	<script src="vendors/isotope/isotope-min.js"></script>
	<script src="vendors/owl-carousel/owl.carousel.min.js"></script>
	<script src="{% static 'home/js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
	<script src="{% static 'home/js/mail-script.js' %}"></script>
	<script src="{% static 'home/js/custom.js' %}"></script>
</body>

</html>

home/templates/home/dashboard.html
{% extends 'home/base3.html' %}
{% load static  %}
{% block title %}
Homepage
{% endblock %}
{% block pre %}


{% endblock %}
{% block content %}

<div class="limiter">
		<div class="container-table100">
			<div class="wrap-table100">
					<div class="table">

						<div class="row header">
							<div class="cell">
								DOC Information
							</div>
							<div class="cell">

							</div>
							<!-- <div class="cell">
								Job Title
							</div>
							<div class="cell">
								Location
							</div> -->
						</div>

						<div class="row">
							<div class="cell" data-title="Full Name">
								First Name:
							</div>
							<div class="cell" data-title="Age">
								{{ info.firstname }}
							</div>
						</div>

						<div class="row">
							<div class="cell" data-title="Full Name">
								Last Name:
							</div>
							<div class="cell" data-title="Age">
								{{ info.lastname }}
							</div>
						</div>

						<div class="row">
							<div class="cell" data-title="Full Name">
								Adhar Number:
							</div>
							<div class="cell" data-title="Age">
                               {{ info.aadharno }}
							</div>
						</div>

						<div class="row">
							<div class="cell" data-title="Full Name">
								Phone Number:
							</div>
							<div class="cell" data-title="Age">
                                {{ info.phoneno }}
							</div>
						</div>

						<div class="row">
							<div class="cell" data-title="Full Name">
								Pincode:
							</div>
							<div class="cell" data-title="Age">
                                {{info.pincode}}
							</div>
						</div>
                        <div class="row">
							<div class="cell" data-title="Full Name">
								Degree:
							</div>
							<div class="cell" data-title="Age">
                                {{info.degree}}
							</div>
						</div>
v



					</div>
			</div>
		</div>
	</div>



<!--===============================================================================================-->
	<script src="{% static 'table/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'table/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'table/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'table/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'table/js/main.js' %}"></script>
</div>

{% endblock %}

home/templates/home/departments.html
<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="icon" href="img/favicon.png" type="image/png">
	<title>Department</title>
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="css/bootstrap.css">
	<link rel="stylesheet" href="vendors/linericon/style.css">
	<link rel="stylesheet" href="css/font-awesome.min.css">
	<link rel="stylesheet" href="vendors/nice-select/css/nice-select.css">
	<link rel="stylesheet" href="vendors/animate-css/animate.css">
	<link rel="stylesheet" href="vendors/jquery-ui/jquery-ui.css">
	<!-- main css -->
	<link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="css/responsive.css">
</head>

<body>

	<!--================Header Menu Area =================-->
	<header class="header_area">
		<div class="top_menu row m0">
			<div class="container">
				<div class="float-left">
					<ul class="left_side">
						<li>
							<a href="login.html">
								<i class="fa fa-facebook-f"></i>
							</a>
						</li>
						<li>
							<a href="login.html">
								<i class="fa fa-twitter"></i>
							</a>
						</li>
						<li>
							<a href="login.html">
								<i class="fa fa-dribbble"></i>
							</a>
						</li>
						<li>
							<a href="login.html">
								<i class="fa fa-behance"></i>
							</a>
						</li>
					</ul>
				</div>
				<div class="float-right">
					<ul class="right_side">
						<li>
							<a href="login.html">
								<i class="lnr lnr-phone-handset"></i>
								012-6532-568-9746
							</a>
						</li>
						<li>
							<a href="#">
								<i class="lnr lnr-envelope"></i>
								emergency@colorlib.com
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<a class="navbar-brand logo_h" href="index.html">
						<img src="img/logo.png" alt="">
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
					 aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
						<div class="row ml-0 w-100">
							<div class="col-lg-12 pr-0">
								<ul class="nav navbar-nav center_nav pull-right">
									<li class="nav-item">
										<a class="nav-link" href="index.html">Home</a>
									</li>
									<li class="nav-item active">
										<a class="nav-link" href="departments.html">Departments</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="doctors.html">Doctors</a>
									</li>
									<li class="nav-item submenu dropdown">
										<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pages</a>
										<ul class="dropdown-menu">
											<li class="nav-item">
												<a class="nav-link" href="about.html">About</a>
											</li>
											<li class="nav-item">
												<a class="nav-link" href="services.html">Services</a>
											</li>
											<li class="nav-item">
												<a class="nav-link" href="elements.html">Elements</a>
											</li>
										</ul>
									</li>
									<li class="nav-item submenu dropdown">
										<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blog</a>
										<ul class="dropdown-menu">
											<li class="nav-item">
												<a class="nav-link" href="blog.html">Blog</a>
											</li>
											<li class="nav-item">
												<a class="nav-link" href="single-blog.html">Blog Details</a>
											</li>
										</ul>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="contact.html">Contact</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</nav>
		</div>
	</header>
	<!--================Header Menu Area =================-->

	<!--================ Banner Area =================-->
	<section class="banner_area">
		<div class="banner_inner d-flex align-items-center">
			<div class="container">
				<div class="banner_content text-left">
					<h2>Procedure Category</h2>
					<div class="page_link">
						<a href="index.html">Home</a>
						<a href="departments.html">Departments</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================End Banner Area =================-->

	<!--================ Procedure Category Area =================-->
	<section class="procedure_category section_gap_custom">
		<div class="container">
			<div class="row justify-content-center section-title-wrap">
				<div class="col-lg-12">
					<h1>Procedure Category</h1>
					<p>
						Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
					</p>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-4 mb-30">
					<div class="categories_post">
						<img src="img/procedure/p1.jpg" alt="Procedure">
						<div class="categories_details">
							<div class="categories_text">
								<div class="border_line"></div>
								<a href="single-blog.html">
									<h5>Emergency Treatment</h5>
								</a>
								<div class="border_line"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4 mb-30">
					<div class="categories_post">
						<img src="img/procedure/p2.jpg" alt="Procedure">
						<div class="categories_details">
							<div class="categories_text">
								<div class="border_line"></div>
								<a href="single-blog.html">
									<h5>Emergency Treatment</h5>
								</a>
								<div class="border_line"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4 mb-30">
					<div class="categories_post">
						<img src="img/procedure/p3.jpg" alt="Procedure">
						<div class="categories_details">
							<div class="categories_text">
								<div class="border_line"></div>
								<a href="single-blog.html">
									<h5>Emergency Treatment</h5>
								</a>
								<div class="border_line"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="categories_post">
						<img src="img/procedure/p1.jpg" alt="Procedure">
						<div class="categories_details">
							<div class="categories_text">
								<div class="border_line"></div>
								<a href="single-blog.html">
									<h5>Emergency Treatment</h5>
								</a>
								<div class="border_line"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4 mb-30">
					<div class="categories_post">
						<img src="img/procedure/p2.jpg" alt="Procedure">
						<div class="categories_details">
							<div class="categories_text">
								<div class="border_line"></div>
								<a href="single-blog.html">
									<h5>Emergency Treatment</h5>
								</a>
								<div class="border_line"></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-lg-4 mb-30">
					<div class="categories_post">
						<img src="img/procedure/p3.jpg" alt="Procedure">
						<div class="categories_details">
							<div class="categories_text">
								<div class="border_line"></div>
								<a href="single-blog.html">
									<h5>Emergency Treatment</h5>
								</a>
								<div class="border_line"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================ End Procedure Category Area =================-->

	<!-- start footer Area -->
	<footer class="footer-area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-2  col-md-6">
					<div class="single-footer-widget">
						<h6>Top Products</h6>
						<ul class="footer-nav">
							<li>
								<a href="#">Managed Website</a>
							</li>
							<li>
								<a href="#">Manage Reputation</a>
							</li>
							<li>
								<a href="#">Power Tools</a>
							</li>
							<li>
								<a href="#">Marketing Service</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4  col-md-6">
					<div class="single-footer-widget mail-chimp">
						<h6 class="mb-20">Contact Us</h6>
						<p>
							56/8, Santa bullevard, Rocky beach, San fransisco, Los angeles, USA
						</p>
						<h3>012-6532-568-9746</h3>
						<h3>012-6532-568-97468</h3>
					</div>
				</div>
				<div class="col-lg-6  col-md-12">
					<div class="single-footer-widget newsletter">
						<h6>Newsletter</h6>
						<p>You can trust us. we only send promo offers, not a single spam.</p>
						<div id="mc_embed_signup">
							<form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
							 method="get" class="form-inline">

								<div class="form-group row">
									<div class="col-lg-7 col-md-6 col-sm-12">
										<input name="EMAIL" placeholder="Your Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your Email Address '"
										 required="" type="email">
									</div>

									<div class="col-lg-5 col-md-12">
										<button class="nw-btn main_btn circle">get started
											<span class="lnr lnr-arrow-right"></span>
										</button>
									</div>
								</div>
								<div class="info"></div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<div class="row footer-bottom d-flex justify-content-between">
				<p class="col-lg-8 col-sm-12 footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				</p>
				<div class="col-lg-4 col-sm-12 footer-social">
					<a href="#">
						<i class="fa fa-facebook"></i>
					</a>
					<a href="#">
						<i class="fa fa-twitter"></i>
					</a>
					<a href="#">
						<i class="fa fa-dribbble"></i>
					</a>
					<a href="#">
						<i class="fa fa-behance"></i>
					</a>
				</div>
			</div>
		</div>
	</footer>
	<!-- End footer Area -->



	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="js/jquery-3.2.1.min.js"></script>
	<script src="js/popper.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="vendors/nice-select/js/jquery.nice-select.min.js"></script>
	<script src="js/jquery.ajaxchimp.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
	<script src="js/mail-script.js"></script>
	<script src="js/custom.js"></script>
</body>

</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static  %}
{% block title %}
Homepage
{% endblock %}
{% block pre %}

{% endblock %}
{% block content %}
<section class="home_banner_area">
		<div class="banner_inner d-flex align-items-center">
			<div class="container">
				<div class="banner_content row">
					<div class="col-lg-12">
						<h1>Welcome ! {{ info.first_name }} </h1>
						<h1>We Care for Your Health Every Moment</h1>
						<p>If you are looking at blank cassettes on the web, you may be very confused at the difference in price You may see some
							for as low as each.</p>
						<a class="main_btn mr-10" href="#">get started</a>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}